version: '2'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"

  redis:
    image: redis
    ports:
      - "6379:6379"

  express:
    build: './web_api'
    ports:
      - "4000:4000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
